global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]

  - job_name: 'postgres-exporter-task'
    static_configs:
      - targets: [ 'postgres-exporter-task:9187' ]

  - job_name: 'postgres-exporter-user'
    static_configs:
      - targets: [ 'postgres-exporter-user:9187' ]